MoneyShare/Controllers/ApplicationDbController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoneyShare.Models;

namespace MoneyShare.Controllers
{
    //[Authorize]
    public class ApplicationDbController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ApplicationDbController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ApplicationDb
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.MemberModels.ToListAsync());
        }

        // GET: ApplicationDb/Details/5
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var memberModel = await _context.MemberModels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (memberModel == null)
            {
                return NotFound();
            }

            return View(memberModel);
        }

        // GET: ApplicationDb/Create
        //[Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: ApplicationDb/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,TwoFactorCode,TwoFactorCodeDateTime,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] MemberModel memberModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(memberModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(memberModel);
        }

        // GET: ApplicationDb/Edit/5
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var memberModel = await _context.MemberModels.FindAsync(id);
            if (memberModel == null)
            {
                return NotFound();
            }
            return View(memberModel);
        }

        // POST: ApplicationDb/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id, [Bind("FirstName,LastName,TwoFactorCode,TwoFactorCodeDateTime,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] MemberModel memberModel)
        {
            if (id != memberModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(memberModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberModelExists(memberModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(memberModel);
        }

        // GET: ApplicationDb/Delete/5
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var memberModel = await _context.MemberModels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (memberModel == null)
            {
                return NotFound();
            }

            return View(memberModel);
        }

        // POST: ApplicationDb/Delete/5
        [HttpPost, ActionName("Delete")]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var memberModel = await _context.MemberModels.FindAsync(id);
            _context.MemberModels.Remove(memberModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MemberModelExists(string id)
        {
            return _context.MemberModels.Any(e => e.Id == id);
        }
    }
}

MoneyShare/Views/Shared/_Layout.cshtml
@using MoneyShare.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<MemberModel> SignInManager
@inject UserManager<MemberModel> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoneyShare</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/fontawesome.css" />
     <script>
        var jwt = sessionStorage.getItem('jwt');
        if (jwt != null && jwt != " ") {
            var requestInfo = { 'method': 'GET', headers: { 'Authorization': 'bearer ' + jwt }, credentials: 'same-origin' };
            fetch('/api/AuthorizeCheck', requestInfo)
                .then(response => {
                    if (response.ok) {
                        document.getElementById('login').classList.add('d-none');
                        document.getElementById('register').classList.add('d-none');
                        document.getElementById('forgotPassword').classList.add('d-none');
                        document.getElementById('adminPanel').classList.add('d-none');
                        document.getElementById('signout').classList.remove('d-none');
                        fetch("/api/AdminCheck", requestInfo)
                        .then(response => {
                            if (response.ok) {
                                document.getElementById('adminPanel').classList.remove('d-none');
                            }
                            else
                            {
                                document.getElementById('adminPanel').classList.add('d-none');
                            }
                        });
                    }
                    else
                    {
                        document.getElementById('login').classList.remove('d-none');
                        document.getElementById('register').classList.remove('d-none');
                        document.getElementById('forgotPassword').classList.remove('d-none');
                        document.getElementById('signout').classList.add('d-none');
                        document.getElementById('adminPanel').classList.add('d-none');

                    }
                });
        }
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MoneyShare</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a id="register" asp-controller="Home" asp-action="Register" class="nav-link text-dark hide-loggedin">Register</a>
                        </li>
                        <li class="nav-item">
                            <a id="login" href="#" class="nav-link text-dark hide-loggedin" data-toggle="modal" data-target="#modalLogin">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a id="forgotPassword" href="#" class="nav-link text-dark hide-loggedin" data-toggle="modal" data-target="#modalForgotPassword">Forgot Password</a>
                        </li>
                        <li class="nav-item">
                            <a id="signout" href="#" class="nav-link text-dark d-none">Sign Out</a>
                        </li>
                        <li class="nav-item">
                            <a id="adminPanel" asp-controller="ApplicationDb" asp-action="Index" class="nav-link text-dark d-none">admin Panel</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MoneyShare - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <div class="modal fade" id="modalLogin">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    Enter your credentials to log in.
                    <span class="text-danger" id="loginStatus"></span>
                </div>
                <div class="modal-body">
                    <div id="loginUsernamePasswordContainer">
                        <div class="form-group">
                            <label for="username">Username:</label>
                            <input type="text" class="form-control" placeholder="Enter your username" id="loginUsername" />
                        </div>
                        <div class="form-group">
                            <label for="password">Password:</label>
                            <input type="password" class="form-control" placeholder="Enter your password" id="loginPassword" />
                        </div>
                    </div>
                    <div class="form-group d-none" id="loginTwoFactorFormGroup">
                        <label for="TwoFactorValue">Enter the six digit code from your email:</label>
                        <input type="password" class="form-control" placeholder="Enter your code" id="loginTwoFactorValue" />
                    </div>
                    <div id="loginSpinner" class="spinner-border text-primary d-none"></div>
                    <button id="loginButton" type="submit" class="btn btn-primary">Log In</button>
                    <button class="d-none btn-primary btn" id="confirmTwoFactorButton" type="submit">Verify Authentication Code</button>
                </div>
            </div>
        </div>
    </div>
        <div class="modal fade" id="modalForgotPassword">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        Fill out the form to reset password.
                        <span class="text-danger"></span>
                    </div>
                <div class="modal-body">
                    <div id="loginUsernamePasswordContainer">
                        <div class="form-group">
                            <label for="firstName">First name:</label>
                            <input type="text" class="form-control" placeholder="Enter your username" id="forgotPasswordFirstName" />
                        </div>
                        <div class="form-group">
                            <label for="lastName">Last name:</label>
                            <input type="text" class="form-control" placeholder="Enter your username" id="forgotPasswordLastName" />
                        </div>
                        <div class="form-group">
                            <label for="username">Username:</label>
                            <input type="text" class="form-control" placeholder="Enter your username" id="forgotPasswordUsername" />
                        </div>
                        <div class="form-group">
                            <label for="email">Email:</label>
                            <input type="email" class="form-control" placeholder="Enter your email" id="forgotPasswordEmail" />
                        </div>
                    </div>
                    <button id="forgotPasswordButton" type="submit" class="btn btn-primary">Send reset link</button>
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/forgotPassword.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>